name: dwart_components
description: Dwart game components and assets
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flame: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter_gen:
  line_length: 80
  assets:
    package_parameter_enabled: true

flutter:
  assets:
    - assets/images/dwarf/
